from django.urls import path
from ..views.account_option import (change_role, get_infor_account, save_infor_candidate, save_image_account, save_job,
                                    check_save, delete_save_job, save_company, delete_save_company, get_save_job,
                                    get_save_company, save_infor_employer, get_info_company_employer,
                                    save_company_employer, save_image_company_employer, edit_job, get_employer_job,
                                    delete_employer_job, get_all_employer_job, apply_job, delete_apply_job,
                                    check_apply, get_apply_job, preview_candidate, delete_employer_company,
                                    delete_info_candidate, save_project_candidate, handle_apply)

urlpatterns = [
    path("change_role/", change_role),
    path("get_info/", get_infor_account),
    path("save_candidate/", save_infor_candidate),
    path("save_employer/", save_infor_employer),
    path("save_image/", save_image_account),
    path("save_job/", save_job),
    path("check_save/", check_save),
    path("delete_save_job/", delete_save_job),
    path("save_company/", save_company),
    path("delete_save_company/", delete_save_company),
    path("get_save_job/", get_save_job),
    path("get_save_company/", get_save_company),
    path("get_info_company_employer/", get_info_company_employer),
    path("save_image_company_employer/", save_image_company_employer),
    path("save_company_employer/", save_company_employer),
    path("edit_job/", edit_job),
    path("get_employer_job/", get_employer_job),
    path("delete_employer_job/", delete_employer_job),
    path("get_all_employer_job/", get_all_employer_job),
    path("apply_job/", apply_job),
    path("delete_apply_job/", delete_apply_job),
    path("check_apply/", check_apply),
    path("get_apply_job/", get_apply_job),
    path("preview_candidate/", preview_candidate),
    path("delete_employer_company/", delete_employer_company),
    path("delete_info_candidate/", delete_info_candidate),
    path("save_project_candidate/", save_project_candidate),
    path("handle_apply/", handle_apply)
]